apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: testing-215306/jenkins-x-quickstart-liberty-2
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
